apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      # nodePort: 31887