apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-list-postgres-data-persisent-volume-claim
spec:
  volumeName: todo-list-postgres-data-persisent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi