apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: ${DOCKER_USERNAME}/task-service:${GITHUB_SHA}
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: "postgres://todo_list:password@todo-list-db-service:5432/todo_list"
            - name: JWT_SECRET
              value: "my-secret"
            - name: PORT
              value: "3001"
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
