apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001
  selector:
    app: task-service