name: Lint-User

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm i
      - uses: sibiraj-s/action-eslint@v3
        with:
          working-directory: ${{ inputs.working-directory }}
          eslint-args: '--config=.eslintrc.json  --output-file=eslint-report-${{ inputs.working-directory }}-${{ github.sha }}.json'
          extensions: 'js'
          annotations: true          
