name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    GitLeaks:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    Lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '22'
        - run: npm i
        - uses: sibiraj-s/action-eslint@v3
          with:
            working-directory: ./task-service
            eslint-args: '--config=.eslintrc.json'
            extensions: 'js'
            annotations: true
        - uses: sibiraj-s/action-eslint@v3
          with:
            working-directory: ./user-service
            eslint-args: '--config=.eslintrc.json'
            extensions: 'js'
            annotations: true

    Snyk:
      runs-on: ubuntu-latest
      needs: [Lint, GitLeaks]
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Run Snyk
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    Trivy:
      runs-on: ubuntu-latest
      needs: [Lint, GitLeaks]
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Generate Trivy Vulnerability Report
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: "fs"
            output: trivy-report.json
            format: json
            scan-ref: .
            exit-code: 0
  
        - name: Upload Vulnerability Scan Results
          uses: actions/upload-artifact@v4
          with:
            name: trivy-report
            path: trivy-report.json
            retention-days: 30

    Sonarcloud:
      name: SonarCloud Analysis
      needs: [Trivy, Snyk]
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          ORG: ${{secrets.SONARQUBE_ORG}}
          PROJECT_KEY: ${{secrets.SONARQUBE_PROJECT_KEY}}

    Tests:
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres:16
          env:
            POSTGRES_USER: test_user
            POSTGRES_PASSWORD: test_password
            POSTGRES_DB: test_todo_list
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Install dependencies
          run: |
            cd ./task-service && npm i
        - name: Run migrations
          run: |
            cd ./task-service && npm run migrate:test
          env:
            TEST_DB_HOST: localhost
            TEST_DB_USER: test_user
            TEST_DB_PASSWORD: test_password
            TEST_DB_NAME: test_todo_list
        - name: Run tests
          run: |
            cd ./task-service && npm run migrate:test
          env:
            TEST_DB_HOST: localhost
            TEST_DB_USER: test_user
            TEST_DB_PASSWORD: test_password
            TEST_DB_NAME: test_todo_list

    Create-Image:
        name: Create Image
        needs: Sonarcloud
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            continue-on-error: false
    
          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: "22"
              registry-url: "https://registry.npmjs.org"
            continue-on-error: false

          - name: Install Docker
            run: |
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
            continue-on-error: false
    
          - name: Install Docker Compose
            run: |
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              docker-compose --version
            continue-on-error: false
          - name: Build application images
            run: docker-compose build --platform linux/amd64
            env:
              DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
              MONGO_INITDB_ROOT_USERNAME: ${{secrets.MONGO_INITDB_ROOT_USERNAME}}
              MONGO_INITDB_ROOT_PASSWORD: ${{secrets.MONGO_INITDB_ROOT_PASSWORD}}
              ME_CONFIG_MONGODB_ADMINUSERNAME: ${{secrets.ME_CONFIG_MONGODB_ADMINUSERNAME}}
              ME_CONFIG_MONGODB_ADMINPASSWORD: ${{secrets.ME_CONFIG_MONGODB_ADMINPASSWORD}}
              ME_CONFIG_MONGODB_URL: ${{secrets.ME_CONFIG_MONGODB_URL}}
              MONGODB_URI_USER_SERVICE: ${{secrets.MONGODB_URI_USER_SERVICE}}
              JWT_SECRET: ${{secrets.JWT_SECRET}}
              MONGODB_URI_TASK_SERVICE: ${{secrets.MONGODB_URI_TASK_SERVICE}}
            continue-on-error: false

          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
            continue-on-error: false
    
          - name: Push Docker images to Docker Hub
            run: |
              chmod +x ./scripts/push-images.sh && ./scripts/push-images.sh fisher1o1 ${{github.sha}}
            continue-on-error: false

#   install_dependencies:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '22'

#       - name: Cache dependencies
#         uses: actions/cache@v3
#         with:
#           path: |
#             ~/.npm
#             api-gateway/node_modules
#             frontend-service/node_modules
#             task-service/node_modules
#             user-service/node_modules
#           key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

#       - name: Install dependencies for all services
#         run: |
#           chmod +x ./scripts/install.sh && ./scripts/install.sh
