name: CI Pipeline with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            api-gateway/node_modules
            frontend-service/node_modules
            task-service/node_modules
            user-service/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies for all services
        run: |
          chmod +x ./scripts/install.sh && ./scripts/install.sh

  build_and_test:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        continue-on-error: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
        continue-on-error: false

      - name: Install Docker using Docker's official script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
        continue-on-error: false

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
        continue-on-error: false

      - name: Build application images
        run: docker-compose build
        continue-on-error: false

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        continue-on-error: false

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-list:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-list:${{ github.sha }}
        continue-on-error: false


    #   - name: Checkout repository
    #     uses: actions/checkout@v2

    #   - name: Set up Docker
    #     uses: docker/setup-buildx-action@v2
    #   - name: Build and start containers using docker-compose
    #     run: |
    #       docker-compose -f docker-compose.yml build
    #       docker-compose -f docker-compose.yml up -d
 

    #   - name: Shut down docker-compose services
    #     run: |
    #       docker-compose down

#   push_docker_images:
#     needs: build_and_test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Push Docker images
#         run: |
#           docker-compose -f docker-compose.yml push api-gateway
#           docker-compose -f docker-compose.yml push frontend-service
#           docker-compose -f docker-compose.yml push task-service
#           docker-compose -f docker-compose.yml push user-service
